#!/usr/bin/env bash
# This is a bash script that transfers a file from a client to a server using scp
path="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd)"
filename=$(basename "$BASH_SOURCE")
file="$1"
ip="$2"
user="ubuntu"
key="/root/.ssh/"

if [ $# -eq 2 ]; then
        scp -i "$key" -o StrictHostKeyChecking=no "$path"/"$file" "$user"@"$ip":/home/"$user"/
else
        echo -e "Usage: $filename PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
